### ISSUE TITLE
Blocks and entities don't drop anything

### ISSUE THREAD

**Issue by JulesFouchy** [NoComment1105/DeepslateCutting#13]
### What happened?

All the blocks I break and all the entities I kill don't drop anything.

### DeepslateCutting and Minecraft Version

deepslatecutting-fabric-1.6.2.jar for Minecraft 1.20.1

### Operating System

Windows 10

### Additional context

The only mods I have installed are yours and fabric API:
![image](https://github.com/NoComment1105/DeepslateCutting/assets/45451201/38df9f50-1d09-4881-8aba-4452d51d0a7a)

**Comment by KAGUYA-1137** [comment]
Same.
My favorite shulkerbox disappeared because of this bug.

**Comment by NoComment1105** [comment]
I can reproduce not being able to break the custom deepslatecutting blocks but not entities, they still drop everything for me

**Comment by NoComment1105** [comment]
Now i can never mind

**Comment by NoComment1105** [comment]
Fixed in latest version
