### ISSUE TITLE
deepslate cutting on fabric 0.12.12 server side indicates broken implementation of modmenu

### ISSUE THREAD

**Issue by TheRanker** [NoComment1105/DeepslateCutting#4]
### What happened?

 - Mod 'Deepslate Cutting' (deepslatecutting) 1.3.0 recommends any version of modmenu, which is disabled for this environment (client/server only)!
	 - You should install any version of modmenu for the optimal experience.

Mod Menu dont load on server side.  unable to correct this error. 

### Relevant log output

```shell
- Mod 'Deepslate Cutting' (deepslatecutting) 1.3.0 recommends any version of modmenu, which is disabled for this environment (client/server only)!
	 - You should install any version of modmenu for the optimal experience.
```

### DeepslateCutting and Minecraft Version

1.3.0

### Operating System

who cares.

### Additional context

unsrue if this will cuase any issues in the future,, but your using a broken code.. and need to stop reqeusting the use of modmenu on server enviroment.

**Comment by NoComment1105** [comment]
This causes zero issues and will continue to do so. Fabric does not have sided reccomendations, and thus this is not me "using a broken code" and I cannot prevent this.
