### ISSUE TITLE
Add deepslate top texture to stairs, slabs and walls.

### ISSUE THREAD

**Issue by teleheel** [NoComment1105/DeepslateCutting#5]
### Related to a problem?

yes

### Describe the related problem

Currently, the added blocks uses the side texture of vanilla deepslate on all the sides. This makes deepslate slabs and stairs stand out when placed on regular deepslate. 

### Describe the soloution you'd like

Change the top textures of the deepslate stairs and slabs to match the regular deepslate top texture. Maybe do the same to the deepslate wall for parity?

### Describe the alternatives considered

None

**Comment by NoComment1105** [comment]
Well that's a giant oversight on my behalf. I shall get that fixed tommorow.

**Comment by NoComment1105** [comment]
It would be against parity, and a bit more painful to change the top texture of the wall. Good shout though! I'm on the bug now, a fix should roll out within the hour
