### ISSUE TITLE
Bug report: Breaks server resource loading

### ISSUE THREAD

**Issue by SilverAndro** [NoComment1105/DeepslateCutting#6]
### What happened?

Some mods (such as server-translations-api) are broken by the maybe-more-data dependency and will fail to load resources. This can be fixed by bringing that library up to date with https://github.com/Draylar/maybe-data/commit/ec4db308106353f4aca05bcc4eb9bdb4767b0780. Please see https://github.com/Draylar/maybe-data/issues/5 as well.

### DeepslateCutting and Minecraft Version

1.3.2

### Operating System

Windows 10

**Comment by NoComment1105** [comment]
Thank you for bringing this to my attention. DS uses a custom for of maybe-data called maybe-more-data that works slightly differently, and has an extra feature that maybe-data doesn't. i will be looking into making a PR for maybe-data before this can be fixed.

**Comment by NoComment1105** [comment]
I've submitted a Pull Request to maybe-data. I'll update DS accordingly once merged

**Comment by NoComment1105** [comment]
I have just releases v1.3.3 which contains a fix for this issue and some general clean up. Have fun!
